Repository RainbowJM/strandeiland, pull requests merged in 2023-06, with the labels that each got.

#47 code refactored
  public/js/script.js
  views/index.ejs
  views/partials/footer.ejs
  views/partials/thumbnail.ejs
Labels: review

#48 Hilal
  public/css/detail-page.css
  public/css/global.css
  public/js/script.js
  views/detailPage-1.ejs
  views/partials/header.ejs
Labels: review

#49 extra partials folder
  public/js/script.js
  views/partials/detailpage/article.js
  views/partials/detailpage/users.js
Labels: review

#50 css feedback from my teammates
  public/css/detail-page.css
Labels: review

#53 filter design done
  public/css/overview-page.css
  public/js/script.js
  views/index.ejs
Labels: review

#67 changed where the chat is set in the layout
  public/css/chat.css
  public/css/detail-page.css
  views/detailPage-1.ejs
Labels: feedback

#70 Service worker
  app.js
  public/css/offline.css
  public/images/apple-touch-icon.png
  public/images/favicon.ico
  public/images/icon-192x192.png
  public/images/icon-256x256.png
  public/images/icon-384x384.png
  public/images/icon-512x512.png
  public/images/logo.png
  public/js/script.js
  public/manifest.json
  public/service-worker.js
  views/offline.ejs
  views/partials/footer.ejs
  views/partials/head.ejs
Labels: enhancement - feature

#71 Detailpage new version (itheration
  public/css/chat.css
  public/css/detail-page.css
  views/detailPage-1.ejs
Labels: documentation

#74 Chat style
  app.js
  public/css/chat.css
  public/js/modules/variables.js
  views/detailPage-1.ejs
Labels: bug

#79 kleine css change
  public/css/detail-page.css
Labels: enhancement - feature

#80 offline state, krijg hem alleen niet gecentered in css
  public/css/offline.css
  views/offline.ejs
Labels: enhancement - feature

#81 Chat style
  app.js
  public/css/chat.css
  public/js/script.js
Labels: feedback

#88 pop up (different type of content) and post form
  app.js
  public/css/form.css
  public/css/sent.css
  public/js/script.js
  views/form.ejs
  views/sent.ejs
Labels: enhancement - feature

#89 Detailpage fetch styling with new designs
  .gitignore
  app.js
  public/css/detail-page.css
  public/css/offline.css
  public/css/style.css
  views/detailPage-1.ejs
  views/index.ejs
  views/partials/thumbnail.ejs
Labels: enhancement - feature

#101 variables exported
  public/js/modules/variables.js
Labels: bug, review

#102 Detailpage fetch styling
  public/css/detail-page.css
  public/js/modules/variables.js
  public/js/script.js
  views/detailPage-1.ejs
Labels: enhancement - feature

#106 Overviewpage redesign responsive and microinterctions
  app.js
  public/css/global.css
  public/css/overview-page.css
  views/index.ejs
Labels: enhancement - feature, review

#107 fix the date
  app.js
  public/css/overview-page.css
  views/index.ejs
  views/partials/latest-thumbnail.ejs
Labels: bug, enhancement - feature

#108 Form
  app.js
  public/css/form.css
  public/js/modules/form.js
  public/js/modules/variables.js
  public/js/script.js
  public/service-worker.js
  views/form.ejs
Labels: enhancement - feature

#112 Detail page fixing bugs - laatste dingetje
  public/css/detail-page.css
Labels: bug

#113 Fetch theme detailpage
  app.js
  public/css/detail-page.css
  public/service-worker.js
  views/detailPage-1.ejs
Labels: enhancement - feature

#115 Form loading state
  app.js
  public/css/form.css
  public/js/script.js
  views/form.ejs
Labels: enhancement - feature

#116 removed unnessary comments
  app.js
  public/css/overview-page.css
  views/index.ejs
Labels: enhancement - feature

#121 Form loading state css
  public/css/form.css
  views/form.ejs
Labels: enhancement - feature

#122 code refactor
  public/css/chat.css
  public/css/form.css
  public/css/global.css
  public/css/offline.css
  public/css/overview-page.css
  public/css/sent.css
  public/css/suggestion.css
  public/css/user.css
  public/js/modules/filter.js
  public/js/script.js
  routes/route.js
  views/form.ejs
  views/sent.ejs
  views/suggestion.ejs
Labels: feedback

#140 Change chat border
  public/css/chat.css
  public/js/modules/filter.js
  public/service-worker.js
Labels: feedback

#141 removed all pixel units
  public/css/chat.css
  public/css/global.css
  public/css/overview-page.css
  public/css/user.css
Labels: review

#144 data from database
  app.js
  public/css/form.css
  public/css/sent.css
  public/js/modules/form.js
  views/form.ejs
  views/sent.ejs
Labels: enhancement - feature

#145 Chat
  public/css/form.css
  public/js/script.js
  routes/route.js
  views/form.ejs
Labels: enhancement - feature

#149 Design review overviewpage
  public/css/chat.css
  public/css/global.css
  public/css/suggestions.css
  public/js/modules/filter.js
  views/partials/filter-menu.ejs
  views/partials/footer.ejs
  views/partials/latest-thumbnail.ejs
  views/partials/selectmenu.ejs
  views/partials/thumbnail.ejs
Labels: enhancement - feature

#150 offline styling fixed
  public/css/offline.css
Labels: bug

#152 Detailpage link to users en bug gefixt van ejs
  public/css/suggestion.css
  public/images/david.png
  public/images/emma.png
  public/images/jaap.png
  public/images/mia.png
  views/suggestion.ejs
  views/user.ejs
Labels: bug

#154 css fix
  public/css/suggestion.css
  views/suggestion.ejs
Labels: bug

#156 fetched the themes in the filter
  public/css/suggestions.css
  views/index.ejs
  views/partials/filter-menu.ejs
Labels: enhancement - feature

#158 Make icon dynamic
  public/css/suggestions.css
  public/css/user.css
  public/js/modules/dynamicIconData.js
  public/js/modules/variables.js
  public/js/script.js
  views/partials/article.ejs
  views/partials/latest-thumbnail.ejs
  views/partials/thumbnail.ejs
Labels: enhancement - feature, feedback

#165 fixed the width of the selectmenu
  public/css/suggestions.css
Labels: bug

#171 img fix
  public/css/suggestion.css
Labels: bug

#172 form vervelende dingen aangepast die niet meekwamen met merge
  public/css/form.css
  views/form.ejs
Labels: bug

#173 Styling form
  public/css/form.css
  public/css/sent.css
  public/js/modules/variables.js
  public/js/script.js
  views/form.ejs
Labels: bug, feedback

#174 i put extra things on the call to action
  views/index.ejs
Labels: enhancement - feature, feedback

#175 alle user links en grotendeels responsiveness detailpage
  public/css/suggestion.css
  views/suggestion.ejs
Labels: enhancement - feature

#178 Fetch theme suggestions page
  public/css/suggestions.css
  routes/route.js
  views/partials/latest-thumbnail.ejs
  views/partials/thumbnail.ejs
Labels: bug, enhancement - feature, feedback

#179 revived a lot of code back, not working completely
  public/css/form.css
  public/js/modules/variables.js
  public/js/script.js
  routes/route.js
  views/form.ejs
Labels: bug

#188 Kleine css change
  public/.DS_Store
  public/css/suggestion.css
Labels: Refactor

#190 alt's en buttons refactored
  views/form.ejs
  views/partials/ambassador.ejs
  views/partials/filter-menu.ejs
  views/partials/header.ejs
  views/partials/latest-thumbnail.ejs
  views/partials/thumbnail.ejs
  views/suggestion.ejs
Labels: refactor, sprint 5

#191 fix bug of theme
  routes/route.js
  views/partials/article.ejs
  views/user.ejs
Labels: bug

#192 img to webp, width heights added in html and styling implemented
  public/css/suggestions.css
  public/images/intro-pic.webp
  views/partials/article.ejs
  views/partials/head.ejs
  views/partials/latest-thumbnail.ejs
  views/partials/thumbnail.ejs
  views/suggestion.ejs
  views/user.ejs
Labels: refactor

#194 Chat bug
  public/css/chat.css
  views/suggestion.ejs
Labels: bug

#202 fixed the overflow + some chat styling
  public/css/chat.css
  public/css/suggestion.css
Labels: bug

#205 the completed version of form
  public/css/form.css
  public/js/modules/form.js
  public/js/script.js
  routes/route.js
  views/form.ejs
Labels: bug, test, review

#206 Update README.md
  README.md
Labels: documentation

#226 error solving TypeError
  public/js/script.js
  public/service-worker.js
Labels: bug

#227 Update README.md
  README.md
Labels: documentation

#228 alles tabbable
  public/css/form.css
  public/css/suggestion.css
  public/js/script.js
  views/form.ejs
  views/suggestion.ejs
  views/user.ejs
Labels: refactor

#230 some changes to enhance the performance of the application
  views/partials/head.ejs
Labels: bug

#234 WHen creating a suggestion, it gets linked to a resident
  routes/route.js
Labels: enhancement - feature, refactor

#235 Lighthouse pwa
  app.js
  gulpfile.js
  package-lock.json
  package.json
  public/css/chat.min.css
  public/css/form.css
  public/css/form.min.css
  public/css/global.min.css
  public/css/offline.min.css
  public/css/sent.min.css
  public/css/suggestion.css
  public/css/suggestion.min.css
  public/css/suggestions.min.css
  public/css/user.min.css
  public/js/script.js
  public/service-worker.js
  routes/route.js
  views/form.ejs
  views/offline.ejs
  views/partials/head.ejs
  views/sent.ejs
  views/suggestion.ejs
  views/user.ejs
Labels: refactor, feedback

#236 Minify removed from some
  public/css/form.min.css
  public/css/suggestion.min.css
  public/service-worker.js
  views/form.ejs
  views/suggestion.ejs
Labels: bug

#238 Readme spell check
  README.md
Labels: documentation

#239 ejs refactor
  views/form.ejs
  views/index.ejs
  views/partials/article.ejs
  views/partials/filter-menu.ejs
  views/partials/footer.ejs
  views/partials/head.ejs
  views/partials/header.ejs
  views/partials/latest-thumbnail.ejs
  views/partials/thumbnail.ejs
  views/partials/users.ejs
  views/sent.ejs
  views/user.ejs
Labels: refactor

#240 Refactor keisha
  public/css/global.css
  public/css/sent.css
  public/css/suggestions.css
  public/css/user.css
Labels: refactor

#241 Code refactor all javascript files
  public/js/modules/filter.js
  public/js/modules/form.js
  public/js/modules/navigationMenu.js
  public/js/modules/variables.js
  public/js/script.js
Labels: refactor

#242 CSS REFACTOR
  public/css/chat.css
  public/css/form.css
  public/css/offline.css
  public/css/sent.css
  public/css/suggestion.css
  views/offline.ejs
  views/sent.ejs
  views/suggestion.ejs
  views/user.ejs
Labels: refactor, sprint 5
